//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAlumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Profesores_Curso = new HashSet<Profesores_Curso>();
            this.Alumnos = new HashSet<Alumnos>();
        }

        // Aunque el campo ya esta tipado, tambien se puede poner requisitos aqui.
        public int id { get; set; }
        [Required]
        [MinLength(3)]
        [DataType(DataType.Date)]
        public string nombre { get; set; }
        [DisplayName("Fecha de inicio")]
        [DataType(DataType.Date)]
        public System.DateTime inicio { get; set; }
        [DisplayName("Fecha de finalizacion")]
        public System.DateTime fin { get; set; }
    
        public virtual ICollection<Profesores_Curso> Profesores_Curso { get; set; }
        public virtual ICollection<Alumnos> Alumnos { get; set; }
    }
}
