//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAlumnos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nacionalidades
    {
        public Nacionalidades()
        {
            this.Alumnos = new HashSet<Alumnos>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Alumnos> Alumnos { get; set; }
    }
}
